### PR TITLE
Add support for Python 3.8

### PR DESCRIPTION
**Pull request by hugovk**
And fix a heading for consistency.

### CODE REVIEW

**Comment by hugovk** [comment]
Looks like the CI has been disabled for this repo.

It passes on my fork: https://travis-ci.org/hugovk/gpxpy/builds/630431345

**Comment by tkrajina** [comment]
Thanks. BTW `dev` is the branch where I already added 3.8. But, yes, I forgot to add a label in `setup.py`. Merged (there) now. I still have a few things to finish there, but it will be in `master` in a week or two.

**Comment by hugovk** [comment]
Thank you!

How about setting the `dev` branch as default on GitHub? That way PRs will be sent there instead of `master` by default. Plus a contributing guide and/or PR template could help too: https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

Also, any thoughts about dropping support for Python 2, which reaches EOL in a couple of days?

* https://python2woop.pw
* https://python3statement.org

**Comment by hugovk** [comment]
Oh, I just saw Python 2 has already been dropped from `dev` 👍

**Comment by tkrajina** [comment]
@hugovk good idea to change the default branch, thanks! I'll add a sentence in the README explaining the branches.

**Pull request closed without merging**
