### PR TITLE
Rewrite parse_time so it understands time zones and microseconds

### LINKED ISSUE #83: Weird behavior between Python 3 and Python 2.7 for timestamps
Hello,

When parsing a GPX where precision is on milliseconds, using Python 2 and gpxpy, no issue to get the correct timestamp value per point. But if I use Python, I end up with a 1s precision and then got duplicate timestamps when recording is less than every seconds and fail to calculate speed compared to previous point.

Are you aware of any issue with Python version and timestamp ?

Regards

In attachement the GPX I use to test.
[Move_2017_02_07_12_21_36_Course.gpx.zip](https://github.com/tkrajina/gpxpy/files/758934/Move_2017_02_07_12_21_36_Course.gpx.zip)

### PR DESCRIPTION
**Pull request by Zverik**
Fixes #83, #114 and #148.

I decided to go with a precompiled regular expression. It should be fast, since there are no `+` or `*` special characters in it. Tested in Python 2.7 and 3.6.

### CODE REVIEW

**Comment by christianhauff** [comment]
Any progress on this PR? I just spent an hour on a timezone problem before I realized that gpxpy just ignores the timezone information.

**Comment by bstadlbauer** [comment]
Would it be possible to merge and release this as some point? Would be really helpful to support time zones :+1:

**Comment by tkrajina** [comment]
Yes, I plan to merge this pull request. Before diving in the code @Zverik do you think this is now the final version or you have more things to commit here?

**Comment by Zverik** [comment]
I think that's final: it's on par with the version we use in our company.

**Comment by bstadlbauer** [comment]
Thanks for merging and releaseing!

**Pull request merged**
