### PR TITLE
remove timezone part from date string

### PR DESCRIPTION
**Pull request by sjol**
passed unit tests on python2.7 (I don't have 3 currently installed)

### CODE REVIEW

**Comment by tkrajina** [comment]
Yes, that makes sense, thanks!

There are just a few changes I'd add here. First, what if instead of `2014-02-02T10:03:18Z` the date string in the GPX is `2014-2-2T10:3:18Z` (without leading zeros in two-digit numbers). In that case your `[0:18]` index will not work as expected.

And, another thing, add a test in `test.py`. Something like:

```
    def test_remove_timezone_from_timestamp(self):
        xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
        xml += '<gpx>\n'
        xml += '<trk>\n'
        xml += '<trkseg>\n'
        xml += '<trkpt lat="35.794159" lon="-5.832745"><time>2014-02-02T10:23:18Z-TIMEZONE_ARTIFACT_HERE</time></trkpt>\n'
        xml += '</trkseg></trk></gpx>\n'
        gpx = mod_gpxpy.parse(xml, parser=self.get_parser_type())
        self.assertEquals(gpx.tracks[0].segments[0].points[0].time, ...)
```

**Comment by sjol** [comment]
Cool, I'll take a look at adding the test as well. 

Not sure if checking for digits without leading zeros, as this is not correct according to https://www.w3.org/TR/xmlschema-2/#isoformats, which I think is what GPX is based.

If we do want support it, I think only a regex could help us, but that might be a bit slow.

**Comment by sjol** [comment]
This should be ready for merging now. Don't know if the regular expression affects performance a lot, but at least it should only be invoked when the time string is shorter than the expected length of 19.

With this PR it works for the gpx files produced by the very useful gps tracking app [LD-log](http://ld-log.com/).

**Comment by tkrajina** [comment]
Merged, thanks!

**Pull request merged**
